
---
- name: "Declaring the prompting variables"
  hosts: localhost
  vars_prompt:
    - name: "packagename"
      prompt: "which package you need to install?"
    - name: "servicename"
      prompt: " which service you need to start?"
    - name: "copy_source"
      prompt: "what is the copy source for index file?"
    - name: "dest_source"
      prompt: "what is the dest path to copy inde file?"

  tasks:
    - name: Installing the httpd
      yum:
        name: "{{ packagename }}"
        state: installed
    - name: Copying the file
      copy:
        src: "{{ copy_source }}"
        dest: "{{ dest_source }}"
        state: present
    - name: Starting the service
      service:
        name: "{{ servicename }}"


