---
-
  hosts: localhost
  tasks:
    - name: "Cloning a repo"
      git:
        repo: 'https://github.com/scmgalaxy/ansible-role-template'
        dest: /home/azureuser/karthick/ansibletest
onerepo.yaml


