---
- name: "Declaring the external variables"
  hosts: localhost
  vars_files:
    - "ext_vars.yaml"
  tasks:
    - name: Installing the httpd
      yum:
        name: "{{ packagename }}"
        state: installed
    - name: Copying the file
      copy:
        src: "{{ copy_source }}"
        dest: "{{ dest_source }}"
        state: present
    - name: Starting the service
      service:
        name: "{{ servicename }}"
 
  
