---
- name: Update web servers
  hosts: web  
  vars:
    #myname: "Mano"
    #age: "18"
    packagename: "httpd"
    servicename: "httpd"
  vars_files:
    - "extern_vars.yaml"
  vars_prompt:
    - name: "packagename"
      prompt: "Which version of HTTPD Do you want to install?"

  tasks:
  - name: Install Apache in centos7
    ansible.builtin.yum:
      name: "{{ packagename }}"
      state: latest
  - name: Copy index.html
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
  - name: Starting a Apache Server
    ansible.builtin.service:
      name: "{{ servicename }}"
      state: started
  - name: Print return information from the previous task
    ansible.builtin.debug:
      #var: myname
      var: packagename
  - name: include default step variables
    include_vars: tasks_var.yaml
  - name: Print return information from the previous task
    ansible.builtin.debug:
      msg: "We have installed {{ packagename }}"
