kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: office-role-binding
  namespace: office
subjects:
- kind: User
  name: employee
  apiGroup: ""
roleRef:
  kind: Role
  name: role-office
  apiGroup: ""
