---
- name: Update web servers
  hosts: localhost

  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: latest
    when: ( ansible_os_family == "RedHat")
  - name: Install Apache in Ubuntu
    apt:
      name: apache2
      state: latest
    when: ( ansible_os_family == "Ubuntu")
... 
