- name: Copy file to Server
  hosts: localhost
  connection: local
  tasks:
  - name: Copy index.html file to server
    ansible.builtin.copy:
      src: ~/joseph/index.html
      dest: /var/www/html/index.html
