- name: clone git repo
  hosts: localhost
  connection: local
  tasks:
  - name: clone git repo
    ansible.builtin.git:
      repo: 'https://github.com/scmgalaxy/ansible-role-template'
      dest: ~/joseph/gitclone
      clone: yes
