- name: Update web servers
  hosts: web
  vars_prompt:
    - name: "packagename"
      prompt: "Which package Do you want to install?"
  tasks:
  - name: Install Apache in centos7
    ansible.builtin.yum:
      name: "{{ packagename }}"
      state: latest
  - name: Starting a Apache Server
    ansible.builtin.service:
      name: "{{ packagename }}"
      state: started
