---
- hosts: web
  tasks:
    - name: create file with content
      file:
         path: /var/www/html/index.html
         state: touch
    - name: Add content
      lineinfile:
            dest: /var/www/html/index.html
            line: Helloooo
